dist: trusty
sudo: false
addons:
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "9"
os:
  - linux
cache: yarn
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=google-chrome-stable
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - npm run lint
  - npm run test:once
  - npm run integration
  - npm run coverage

# deployment
after_success:
  - cd dist/
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: franz.becker@itemis.de
  api_key:
    secure: CG1l2GljciydTsEq30cMKrfyyeT6nOjnxqA5aL+ZKNmAy7y/Av41iBK8PjxVUpYGBhWLmvizdLiSvRgX8aptU2EQNZTThIj2Q8FrUqvRRDGveIcSm0yrA+mTz5apoRJI5hYarYoR4woOH4jQGDjyNn+lL+Dp7QmlYcAhmtH8D8Vn+rBMv8m72GEKJVAJVljMnzwFGa5E9R6HRlp0BPRqnuTolW0XPx280Dsx4by94uj/i69RAhYUxUVtprehArTQwIKeXJEwUaSMrRNp/Jj9QGZqbje5BKiNkIPXkI1r9XXZB/5b7goUlACubcZVT/yMAfQF9nECsqz52CskASImL0TRIPulj8+OyZQoCI2ZHaWYTyJ/uxgrZmH/l90vwtin4+xmro7mk1e+Sv0kkcqP9H5XvUJfLjGwyjI8dKilGVwWLtycgBXDD9cEwcLX89qYoazB+OdD95GNlLfbviMwjelpf0Xjx0G0h4Q0OqHuF7ul08+AzVhIzkYbYCbjrWeBVw1+qBBRPx33L3cRdGxticody7fvBn499MRE764Xo7CZ/Qi601IXPuWeG2LdhwEVB8PyZLOpAv8CxupvM9/BmaBUrrPGJvpOQp/GXrnj3DQ3bDp3hApXVd7UP+vimUhbbDzbPeFo2pAvb1Qo126qVqbTO41onCk1JE/CdIFtG4Y=
  on:
    tags: true
    repo: test-editor/web-messaging-service
    node: "6"
