dist: trusty
sudo: false
addons:
  firefox: "58.0.1"
  chrome: stable
  apt:
    packages:
      - xvfb
      - libexif-dev
      - udev
language: node_js
node_js:
  - "9"
os:
  - linux
cache: yarn
before_install:
  # Use a virtual display.
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  # Install latest chrome.
  - export CHROME_BIN=google-chrome-stable
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --version
  - which google-chrome-stable
install:
  - yarn install
script:
  - npm run lint
  - npm run test:once
  - npm run integration
  - npm run coverage

# deployment
after_success:
  - cd dist/
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; bash tag_with_new_patch_version.sh; fi'
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "vxMbhUTRLcGCpnGeg5ztDlK+FM+QgJ1flfrx1wD/iA/yXnW6uNbsSihhtDo3lG/OBX3PiNNRgHAGoORfItZfzzOo2bJhtUGPnxrwprfIPJ4o6w1gZxBOGDtnWLNLbwKr04oK/CUB9jV3xXNswFNdNJwIEJyE17lDqu6D9d+Dr9hguygF5PAp4IGqHfNt1SC870FNtY8bJTCrV0f3L90/8Z14mMf9FsUvNJMF+vZiteeUJGunRgYjG/AenM2Yf8jz2ONFSAnyM02QiSub9kK27SOVD0WuDXd7un7UvtJanmgCO7F6wxOJfOIPPNVNODVzT51c2f+Hz2o3HMrNVTiXsEKuZIDxbxYvPl10lhywmDqe06p3UHNezT+O0gYxP3lmeIpIa/dSDkNJpTraPkg89jmdfjnXCd+t3+ag1Qo4iBgGHD16a1Ru2w4NAWz7m1dh7LqPNmZ+ZKOZcSPQ6axn3h3BeiFFmHdmWtouCLwqdm6Kbeh/a6UNMNXsxu6ZJcD5dNC5yU3RF/8nB4pNXg2aSIfslmXQcUrZqcoX/USdbj+ZQxCLJTajjqCaedvGQpFAgqKHJGHBm9epJBpZ2fUj7eJCsrC7e7NrhaPNK70TKNPJ9ZVNJVaUYaeCRw2vnlKT2dY7rfYbgA7TCkghSWqnx2bSnfcB45urHEeJCV51UH8="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-messaging-service
    node: "9"
