language: nix
sudo: false
before_install:
- sudo mkdir -p /etc/nix
# make sure no browser is left over that can disturb the karma tests (nix-shell provides the browsers!)
- sudo apt-get remove google-chrome-stable -y
- sudo apt-get remove chromium-browser -y
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

env:
  global:
    - # GitHub Environment variables for NPM version patch
    - secure: "lgGiX9lLGcWqFlOtWPYRE+s9kpHGh+UfDCyvBfzKz0VmYOREh7RG9Fv94IiNXwn8kHwKGw9QpVL9wwK9r5fpiIR4I3xq5Hd7RyEdEphrc1trBBRnebu2fP95ub6g8G2M7ldFcmYDX1GKtJqW3bikW0Q9zjOXqY5DGGv+19WPV/fLewP2GC5iKJ5Nk9Ajtd8ZSjxEvPA4JgYS/ZM0yL0LOizZ9UnYRUcuwzfiLyoP6hckA1Ew3Xq2OBjEnxdM4PhMz/vyzYWSqQHn2E+bM6+/Uofpjda/2o8mf9sa9ganNul98j4dB9H1ZvM2syJB3YsXHST1p51+67SwZG5xQxTahfZhCNgSX5HB35TsVIPJYURBGuD2ED4PtGtxSKLrtfrFvFe4wv1DY3KaTCs5PJAd4xEhkhGKUs25vnc64n9spOv3cvrQFVrjLB/iatDvECGJz1Z7tQq2gvFAvzX8h+VKwNd9TljzsguVpZmbavyIfHwURwQo7lI/pbFeIwY3KPRLRbXwtsDSQq41o/QYmZml3kuY+cqpAn+aPeObOj2ttQyzX3KXgaJZLKtNn5q8kLzjY0rgb4iBN5hTm0ovI4le9d5eAqVxK9X8Pd+o4132qFUreBtdebYn6gZzOzALGuxEMM8tz6xVYVIAOfRP/EdmBtirH0ZqfmzI6MRdZuR+I8A="
    - secure: "E+HXoP7a8r9orgwrsQJqwamkrYqAD7sfkDqMYQpsZ2Z83Ptf54XIyYwp2VqCNaoO97QeHFfG7zRLdeNjUrUCOBWG95YmpBZTyqebd9PM7xCYeHeu1kfP2B2sFmpQJotxUs/Wf5zwao0zKmQIzcLrrF7lvheOlMwPCMpvkYPVG0qOx4VF738xvoHbi4E6wJeq4mlW12NFRkkZlDltwCKX/p8Zf41G1OoRTVkPZCkO2jHNrQxh0861HsysFK0Yfk6dbQIJ7z9BC9GtR4i75VVISunyy4njxvN1drfhK+H+CDX15ZH86Zbwqant9Qdny0aGqEJs7k8Jxy1YB10Psve1K11bYm1sm8uKFKeLhsgpM82xS3mJYIVcO45ki81sWXpLRxY34bZ90DqitVIAeiEfr3TELHZfV50r2u5mWrHGbEnixSKEiImE2NU4URMep2GQXn0fgjlRxzsZ+GICB+kyUmVroXVifxMaZacuiOUJQxRmbFRDeTX2JEnN8VKGnZrYs+zgm2xTTEOWR/2XvRJPPJkXWk55lYHV2CkNH0JWafVJYM4UnXn3WcFWKGcI9K4wnj1QRhJXX1s31LqZdA8ZLJAqi2c9Guz0Kuzxxa6c0b9JuS79HOS5OBMZ8bnWbmNwQgr6pk9LjaPJc5AWnHWmTBUlCuzsgltpRPYN25fDDyA="
    - NIXPKGS_ALLOW_UNFREE: 1

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="60-esr"

install:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn install"
script:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "firefox --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "google-chrome --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run lint"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run test:once"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run e2e"

# deployment
after_success:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run packagr"
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; nix-shell shell-${FIREFOX_VERSION}.nix --command  "bash tag_with_new_patch_version.sh"; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: testeditor.eng@gmail.com
  api_key:
    secure: "kA+B5XGZMjwA+aMBLRuontnL6vHvR6A39NLZWUb5m9A9ERex00anfl/cMbQtc8oqQw3hyoc+KfY21b55NiciO+zk7rL4GbG/lKLy0oP8aI2HuVBXQG6kvoVxqv5OA4aPRd3JbfaWL9DtdLMUhKl8ZYAhJw2atJL5fbnwW5VUQ5muhQlxo/aEcZHeAfKfsxRu1HNSPH2e48g7S6vV/CBTOyp1MB0w5wnQUzfa1P02LmQO6moVEG/s9Q6v+ULFQ8QTgPYDLubO6Gn0chaUgYWcO+3E4QwqiAUM8w1G/GtcmijzzRLrWoZAtD0bUwwhjyEcOjvbL5ljc89igCs42XUQr3RQ0+cYGTJvRf3Qpj1Yl3WTutHSrf/Kkf4/Odx2h7GBkEYakGwKUn70Xp4+MtiA7YQovewJ9e28A9aiqpuhc1QZX8lqd9UYkm+32Kl1TEBoRhQVXGWTxeQ8DgxfCElHvffBxGeV9JfvKhC3hRU6seGl8EFlgXlLvmPMh9q8xCYLFmJkDp1iVhOJK6K8gMCRhXoLOlCHrAlAfFfbx5wqFgpdJiCYFDxt515BZOFITchb64hu0kwjUbVPlNre627Cvu8GFU2vzzF1W+xHCu/OllPMsggZb5Os55AmudVBeHefM8s1/eSiW4Xse0hMMBcXVy9G12kOnagD7q8ufeJcMlQ="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-messaging-service

