dist: trusty
sudo: false
addons:
  firefox: "58.0.1"
  chrome: stable
  apt:
    packages:
      - xvfb
      - libexif-dev
      - udev
language: node_js
node_js:
  - "9"
os:
  - linux
cache: yarn
before_install:
  # Use a virtual display.
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  # Install latest chrome.
  - export CHROME_BIN=google-chrome-stable
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --version
  - which google-chrome-stable
install:
  - yarn install
script:
  - npm run lint
  - npm run test:once
  - npm run integration
  - npm run coverage

# deployment
after_success:
  - cd dist/
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: zdPjFElIsbKYXJ0AZ9tO5pdiCPZFE4Olvj/CMGeQR7TJ4rpiMOLotkaQWoMYHr7j1QFdJ7ox7WLyxSPY5lOUAQ2QuhMRq20SZ4xkWd0FYg45jaPfSd9jcLFUyKwL52ZiThalNR/9T8+8BMerq1+NS/SMkseLrleUBxutWTIPY/xLvxOdxIsBIUn2dKoxRPiZP0ESKBLZyzSQZZbZnAkmcxPPWW9TDp14UYcOP0w5QILExdd1Ryg2c8AjjtU7NWr0HWc/XIxBMxjD1uLpjTLGfCB7e/4s3pLbsS7o2YrpYFmzz1v75uqCzmtSRAwMhTIrbPLL4pdLCQKuXtx1FUf/JqsqEbY079zKliHPNYxeD6cu7xHzHfnWBZvIIjA3OrxLL+t5lEdzuAcu4Qf4Re8yI7zkMl/fNcYPQN2hIh/v5uMk/weMzPTz3gawenhamGYdPk/hPeIhrvcLDWdr+PL77EaTFFa6gJreAfVZq+vEhoGTWoaVjGNA4+szh3btiRaAoY7gIlhzTm0VAdKo8ZXIAgErCS3nQKlpgNd5r6qSGeniJk1UhVz6uCgTBg9vtE7tsNq+OO0TSp9HkwjWVb/XbIHoAn/s9bPNea8+f1kPUbVPqzZG1RoVbOUez4u3thvV6PP4z+f6STD2HuzvA6mh7E87KkELmgQdfaWj6N+PlEg=
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-messaging-service
    node: "9"
